package com.ationet.androidterminal.core.domain.model.configuration

import com.ationet.androidterminal.core.domain.model.configuration.Configuration.Companion.Defaults

data class Ationet(
    val nativeUrl: String = Defaults.DEFAULT_NATIVE_URL,
    val visionUrl: String = Defaults.DEFAULT_VISION_URL,
    val gcUsername: String = Defaults.DEFAULT_USERNAME_CC,
    val gcPassword: String = Defaults.DEFAULT_PASSWORD_CC,
    val ccUsername: String = Defaults.DEFAULT_USERNAME_GC,
    val ccPassword: String = Defaults.DEFAULT_PASSWORD_GC,
    val loyaltyUsername: String = Defaults.DEFAULT_USERNAME_LOYALTY,
    val loyaltyPassword: String = Defaults.DEFAULT_PASSWORD_LOYALTY,
    val terminalId: String = Defaults.DEFAULT_TERMINAL_ID,
    val promptConsumerCard: Boolean = Defaults.DEFAULT_PROMPT_CONSUMER_CARD,
    val promptLoyalty: Boolean = Defaults.DEFAULT_PROMPT_LOYALTY,
    val promptGiftCard: Boolean = Defaults.DEFAULT_PROMPT_GIFT_CARD,
    val promptAmountTransaction: Boolean = Defaults.DEFAULT_PROMPT_AMOUNT_TRANSACTION,
    val promptsDefault: Boolean = Defaults.DEFAULT_PROMPTS_DEFAULT,
    val promptAttendantIdentification: Boolean = Defaults.DEFAULT_PROMPTS_DEFAULT,
    val promptDriverIdentification: Boolean = Defaults.DEFAULT_PROMPTS_DEFAULT,
    val promptVehicleIdentification: Boolean = Defaults.DEFAULT_PROMPTS_DEFAULT,
    val promptOdometer: Boolean = Defaults.DEFAULT_PROMPTS_DEFAULT,
    val promptEngineHours: Boolean = Defaults.DEFAULT_PROMPTS_DEFAULT,
    val promptTrailer: Boolean = Defaults.DEFAULT_PROMPTS_DEFAULT,
    val promptMiscellaneous: Boolean = Defaults.DEFAULT_PROMPTS_DEFAULT,
    val promptTruckUnit: Boolean = Defaults.DEFAULT_PROMPTS_DEFAULT,
    val promptSecondaryTrack: Boolean = Defaults.DEFAULT_PROMPTS_DEFAULT,
    val promptPrimaryPIN: Boolean = Defaults.DEFAULT_PROMPTS_DEFAULT,
    val promptSecondaryPIN: Boolean = Defaults.DEFAULT_PROMPTS_DEFAULT,
    val localAgent: Boolean = Defaults.DEFAULT_LOCAL_AGENT,
    val localAgentIp: String = Defaults.DEFAULT_LOCAL_AGENT_IP,
    val localAgentPort: String = Defaults.DEFAULT_LOCAL_AGENT_PORT,
    val ationetVisionVehicleId: Boolean = Defaults.DEFAULT_PROMPTS_DEFAULT,
    val paymentMethodEnabled: Boolean = Defaults.DEFAULT_PROMPTS_PAYMENT_METHOD_ENABLED,
    val loyaltyPaymentMethodEnabled: Boolean = Defaults.DEFAULT_PROMPTS_LOYALTY_PAYMENT_METHOD_ENABLED,
    )